---
# actions/labeler configuration: https://github.com/marketplace/actions/labeler

# Default GitHub Labels: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels

# Add `documentation` label
documentation:
  # to any changes of markdown files on any folder or subfolders
  - '**/*.md'
  # to any changes within docs folder
  - docs/**

# Add `helm-charts` label
helm-charts:
  # to any changes within `charts` directory
  - charts/**

# Add `devcontainer` label
devcontainer:
  # to any changes within .devcontainer folder
  - .devcontainer/**

# Add `github-workflow` label
github-workflow:
  # to any changes within .github folder
  - .github/**

# Add `vscode-settings` label
vscode-settings:
  # to any changes within .vscode folder
  - .vscode/**

# Add `git-config` label
git-config:
  # to any changes within .git folder
  - .git/**
  # to any changes to .gitattributes file
  - .gitattributes
  # to any changes to .gitignore file
  - .gitignore
  # to any changes within .githooks folder
  - .githooks/**

# Add `lint` label
lint:
  # to any changes to files, folders and subfolders with `lint` keyword
  - '**lint**'
