---
# Configuration for .github/workflows/release-drafter.yml

name-template: 'v$RESOLVED_VERSION 📢'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    # label: 'chore'
    labels:
      - documentation    # label from .github/labeler.yml
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'    # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - java    # label from .github/labeler.yml
  minor:
    labels:
      - 'minor'
      - dependencies    # label from .github/labeler.yml
      - maven    # label from .github/labeler.yml
      - gradle    # label from .github/labeler.yml
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
