{{- if .Values.openshift.route.enabled }}
# Expose application via OpenShift route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demoapp-frontend.fullname" . }}
  {{- with .Values.openshift.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "demoapp-frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host }}
  {{- end }}
  path: {{ .Values.openshift.route.path }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "demoapp-frontend.fullname" . }}
    weight: 100
  {{- with .Values.openshift.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}